---
language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/spec/fixtures/modules
install:
  - bundle install --without development system_tests --path=${BUNDLE_PATH:-vendor/bundle}
  - bundle exec rake spec_prep
before_install: rm Gemfile.lock || true
script: bundle exec rake test
branches:
  only:
  - master
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- 2.2
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 3.8"
  - PUPPET_GEM_VERSION="~> 4.0"
matrix:
  fast_finish: true
  exclude:
  - rvm: 2.2
    env: PUPPET_GEM_VERSION="~> 3.8"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 4.0"
