---
name: 'test_build'

'on':
  pull_request:
    branches:
      - 'main'

jobs:
  test_build:
    uses: broadinstitute/shared-workflows/.github/workflows/puppet-test-deploy.yml@v1.4.0
    with:
      puppet_package_name: broadinstitute-qpage
