---
name: 'test_build'

'on':
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  test_build:

    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout repo'
        uses: 'actions/checkout@v2'

      - name: 'Set up Ruby'
        uses: 'ruby/setup-ruby@v1'
        with:
          ruby-version: 2.4

      - name: Get full Ruby version
        id: full-ruby-version
        run: |
          echo ::set-output name=version::$(ruby -e 'puts RUBY_VERSION')

      - name: 'Cache Ruby'
        uses: 'actions/cache@v1'
        with:
          path: 'vendor/bundle'
          key: ${{runner.os}}-${{steps.full-ruby-version.outputs.version}}-v1-gems-${{hashFiles('**/Gemfile.lock')}}
          restore-keys: |
            ${{ runner.os }}-${{ steps.full-ruby-version.outputs.version }}-v1-gems-

      - name: 'Install ruby dependencies'
        run: |
          gem install bundler
          bundler --version
          bundle config path vendor/bundle
          bundle config set with 'development'
          bundle install --jobs 4 --retry 3

      - name: 'Module build'
        run: 'bundle exec rake module:build'

      - name: 'Test module install'
        run: 'bundle exec puppet module install pkg/puppet-qpage-*.tar.gz'
